/**
 * Content banks for in-chat games. IDs are stable strings — sessions store
 * used IDs per match so prompts rotate without repeats until exhausted.
 * contentVersion is stamped into session state for future migrations.
 */

const CONTENT_VERSION = 1;

// [id, optionA, optionB]
const THIS_OR_THAT = [
  ['tot_001', 'Coffee', 'Tea'],
  ['tot_002', 'Beach vacation', 'Mountain cabin'],
  ['tot_003', 'Early bird', 'Night owl'],
  ['tot_004', 'Cats', 'Dogs'],
  ['tot_005', 'Cook at home', 'Eat out'],
  ['tot_006', 'Summer', 'Winter'],
  ['tot_007', 'Books', 'Movies'],
  ['tot_008', 'City life', 'Countryside'],
  ['tot_009', 'Sweet', 'Savory'],
  ['tot_010', 'Plan everything', 'Go with the flow'],
  ['tot_011', 'Texting', 'Calling'],
  ['tot_012', 'Big party', 'Small gathering'],
  ['tot_013', 'Khorovats', 'Sushi'],
  ['tot_014', 'Sea', 'Sevan'],
  ['tot_015', 'Concert', 'Museum'],
  ['tot_016', 'Sneakers', 'Dress shoes'],
  ['tot_017', 'Window seat', 'Aisle seat'],
  ['tot_018', 'Breakfast', 'Brunch'],
  ['tot_019', 'Road trip', 'Flight'],
  ['tot_020', 'Karaoke', 'Board games'],
  ['tot_021', 'Spicy food', 'Mild food'],
  ['tot_022', 'Gym', 'Hike'],
  ['tot_023', 'Save it', 'Spend it'],
  ['tot_024', 'Lahmajun', 'Pizza'],
  ['tot_025', 'Dance all night', 'Deep talk all night'],
  ['tot_026', 'Surprise me', 'Tell me the plan'],
  ['tot_027', 'Old movies', 'New releases'],
  ['tot_028', 'Tan', 'Coffee with milk'],
  ['tot_029', 'Astrology', 'Science'],
  ['tot_030', 'Text back instantly', 'Reply when free'],
  ['tot_031', 'Mountains of Dilijan', 'Streets of Yerevan'],
  ['tot_032', 'Homemade gata', 'Fancy dessert'],
  ['tot_033', 'One best friend', 'Big friend group'],
  ['tot_034', 'Morning shower', 'Night shower'],
  ['tot_035', 'Adventure', 'Comfort'],
  ['tot_036', 'Duduk', 'DJ set'],
  ['tot_037', 'First date: dinner', 'First date: walk'],
  ['tot_038', 'Share fries', 'Order your own'],
  ['tot_039', 'Live to work', 'Work to live'],
  ['tot_040', 'Toasts at dinner', 'Quiet dinner'],
].map(([id, a, b]) => ({ id, a, b }));

// [id, question]
const QUESTION_ROULETTE = [
  ['qr_001', "What's a small thing that instantly makes your day better?"],
  ['qr_002', 'What would you do with a totally free Saturday?'],
  ['qr_003', "What's the best meal you've ever had?"],
  ['qr_004', "What's something you're weirdly good at?"],
  ['qr_005', 'If you could live anywhere for one year, where?'],
  ['qr_006', "What's a movie you can rewatch forever?"],
  ['qr_007', "What's the most spontaneous thing you've done?"],
  ['qr_008', 'What did you want to be when you were 8?'],
  ['qr_009', "What's your comfort food?"],
  ['qr_010', "What's a song that always gets you moving?"],
  ['qr_011', 'Mountains at sunrise or sea at sunset — and why?'],
  ['qr_012', "What's one thing on your bucket list?"],
  ['qr_013', 'What do your friends come to you for?'],
  ['qr_014', "What's the last thing that made you laugh hard?"],
  ['qr_015', 'What tradition means the most to you?'],
  ['qr_016', "What's a skill you want to learn?"],
  ['qr_017', 'Ideal Sunday morning: describe it.'],
  ['qr_018', "What's the best advice you've ever gotten?"],
  ['qr_019', 'What place feels most like home?'],
  ['qr_020', "What's something you changed your mind about?"],
  ['qr_021', 'Who in your family are you most like?'],
  ['qr_022', "What's your go-to karaoke song?"],
  ['qr_023', 'What would your perfect little shop sell?'],
  ['qr_024', "What's a smell that brings back memories?"],
  ['qr_025', 'What are you lowkey proud of?'],
  ['qr_026', 'City break or nature escape — and where?'],
  ['qr_027', "What's the best gift you've ever given?"],
  ['qr_028', 'What always makes you feel like a kid again?'],
  ['qr_029', "What's one thing you'd tell your younger self?"],
  ['qr_030', 'What does a perfect evening look like?'],
].map(([id, question]) => ({ id, question }));

// [id, emoji, answer, altAnswers, category]
const EMOJI_RIDDLES = [
  ['er_001', '🦁👑🌍', 'The Lion King', ['lion king'], 'movie'],
  ['er_002', '🚢🧊💔', 'Titanic', [], 'movie'],
  ['er_003', '🕷️🧑🏙️', 'Spider-Man', ['spiderman', 'spider man'], 'movie'],
  ['er_004', '🧙💍🌋', 'The Lord of the Rings', ['lord of the rings', 'lotr'], 'movie'],
  ['er_005', '🦈🎶😱', 'Jaws', [], 'movie'],
  ['er_006', '👽📞🚲', 'E.T.', ['et', 'e t'], 'movie'],
  ['er_007', '🏠🎈👴', 'Up', [], 'movie'],
  ['er_008', '🤖❤️🌱', 'WALL-E', ['walle', 'wall e'], 'movie'],
  ['er_009', '❄️👭⛄', 'Frozen', [], 'movie'],
  ['er_010', '🃏🦇🌃', 'The Dark Knight', ['dark knight', 'batman'], 'movie'],
  ['er_011', '🧜‍♀️🌊🦀', 'The Little Mermaid', ['little mermaid'], 'movie'],
  ['er_012', '🍫🏭🎫', 'Charlie and the Chocolate Factory', ['willy wonka', 'chocolate factory'], 'movie'],
  ['er_013', '⚡🧑‍🎓🦉', 'Harry Potter', [], 'movie'],
  ['er_014', '🦖🏝️🧬', 'Jurassic Park', ['jurassic world'], 'movie'],
  ['er_015', '🐼🥋🍜', 'Kung Fu Panda', [], 'movie'],
  ['er_016', '🌆🇦🇲🏛️', 'Yerevan', [], 'place'],
  ['er_017', '⛰️🕊️📖', 'Ararat', ['mount ararat', 'masis'], 'place'],
  ['er_018', '🌊🏔️🐟', 'Lake Sevan', ['sevan'], 'place'],
  ['er_019', '🗼❤️🥐', 'Paris', [], 'place'],
  ['er_020', '🗽🍎🚕', 'New York', ['new york city', 'nyc'], 'place'],
  ['er_021', '🎰🌵🎲', 'Las Vegas', ['vegas'], 'place'],
  ['er_022', '🏛️🍝🛵', 'Rome', [], 'place'],
  ['er_023', '🌸🗻🍣', 'Tokyo', ['japan'], 'place'],
  ['er_024', '🐫🔺🐪', 'Egypt', ['pyramids', 'cairo'], 'place'],
  ['er_025', '💃🥘☀️', 'Spain', ['barcelona', 'madrid'], 'place'],
  ['er_026', '🕺🌙🎶', 'Dancing in the Moonlight', [], 'song'],
  ['er_027', '☔👩🎤', 'Umbrella', [], 'song'],
  ['er_028', '💛🚕', 'Yellow', [], 'song'],
  ['er_029', '🔔🔔🔔', 'Jingle Bells', [], 'song'],
  ['er_030', '🌉🔥💧', 'London Bridge Is Falling Down', ['london bridge'], 'song'],
].map(([id, emoji, answer, altAnswers, category]) => ({ id, emoji, answer, altAnswers, category }));

module.exports = {
  CONTENT_VERSION,
  THIS_OR_THAT,
  QUESTION_ROULETTE,
  EMOJI_RIDDLES,
};
