-- AlterTable
ALTER TABLE "users" ADD COLUMN     "dailyLikesResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dailyLikesUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailySuperLikesResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dailySuperLikesUsed" INTEGER NOT NULL DEFAULT 0;
