#!/usr/bin/env node
/**
 * Development startup script with ngrok tunnel for API.
 *
 * Use this when your phone and computer are on different networks,
 * or when local IP connectivity doesn't work (corporate WiFi, etc.)
 *
 * Prerequisites:
 * 1. npm install (ngrok is in devDependencies)
 * 2. Set NGROK_AUTHTOKEN environment variable (get free token at ngrok.com)
 *
 * Usage: node scripts/dev-tunnel.js
 *        npm run dev:tunnel
 */
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const API_PORT = process.env.API_PORT || 3000;
const ROOT_DIR = path.join(__dirname, '..');
const MOBILE_DIR = path.join(ROOT_DIR, 'mobile');

let ngrok;

function createEnvFile(apiUrl) {
  const envLocalPath = path.join(MOBILE_DIR, '.env.development.local');
  const envContent = `# Auto-generated by dev-tunnel.js - DO NOT COMMIT
# Generated at: ${new Date().toISOString()}
# Using ngrok tunnel for API

EXPO_PUBLIC_API_URL=${apiUrl}
EXPO_PUBLIC_SOCKET_URL=${apiUrl}
`;

  fs.writeFileSync(envLocalPath, envContent);
  return envLocalPath;
}

async function startNgrokTunnel() {
  try {
    ngrok = require('@ngrok/ngrok');
  } catch {
    console.error('❌ ngrok is not installed. Run: npm install');
    console.error('   Then set NGROK_AUTHTOKEN (get free token at https://ngrok.com)\n');
    process.exit(1);
  }

  if (!process.env.NGROK_AUTHTOKEN) {
    console.error('❌ NGROK_AUTHTOKEN environment variable is not set.');
    console.error('   1. Sign up for free at https://ngrok.com');
    console.error('   2. Get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken');
    console.error('   3. Set it: export NGROK_AUTHTOKEN=your_token_here\n');
    process.exit(1);
  }

  console.log('🚇 Starting ngrok tunnel for API...');

  const listener = await ngrok.forward({
    addr: API_PORT,
    authtoken: process.env.NGROK_AUTHTOKEN,
  });

  return listener.url();
}

async function start() {
  console.log('\n🚀 Starting Hantibink Development Environment (Tunnel Mode)\n');

  // Start ngrok tunnel
  let tunnelUrl;
  try {
    tunnelUrl = await startNgrokTunnel();
  } catch (err) {
    console.error('❌ Failed to start ngrok tunnel:', err.message);
    process.exit(1);
  }

  console.log(`✅ API tunnel ready: ${tunnelUrl}\n`);

  // Create .env.development.local with tunnel URL
  const envPath = createEnvFile(tunnelUrl);
  console.log(`✅ Created ${path.relative(ROOT_DIR, envPath)}\n`);

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📱 Open your development build app and scan the QR code below');
  console.log('   Your app will connect to the API via ngrok tunnel');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // Start API and Expo concurrently
  // Using Expo's --tunnel for Metro as well
  const concurrently = spawn(
    'npx',
    [
      'concurrently',
      '--names',
      'API,EXPO',
      '--prefix-colors',
      'blue,magenta',
      '--kill-others-on-fail',
      'npm run api',
      'cd mobile && npx expo start --dev-client --tunnel',
    ],
    {
      stdio: 'inherit',
      shell: true,
      cwd: ROOT_DIR,
    }
  );

  concurrently.on('error', (err) => {
    console.error('❌ Failed to start:', err.message);
    cleanup();
    process.exit(1);
  });

  concurrently.on('close', (code) => {
    cleanup();
    if (code !== 0) {
      console.log(`\n⚠️  Process exited with code ${code}`);
    }
    process.exit(code);
  });

  // Handle Ctrl+C gracefully
  process.on('SIGINT', () => {
    console.log('\n\n👋 Shutting down...');
    concurrently.kill('SIGINT');
    cleanup();
  });
}

async function cleanup() {
  if (ngrok) {
    try {
      await ngrok.disconnect();
    } catch {
      // Ignore cleanup errors
    }
  }
}

start().catch((err) => {
  console.error('❌ Error:', err.message);
  cleanup();
  process.exit(1);
});
