#!/usr/bin/env node
/**
 * Development startup script for Hantibink.
 *
 * This script:
 * 1. Detects your local IP address
 * 2. Creates mobile/.env.development.local with the API URL
 * 3. Starts both the API server and Expo Metro bundler
 *
 * Usage: node scripts/dev-start.js
 *        npm run dev
 */
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const qrcode = require('qrcode-terminal');
const { getLocalIP } = require('./get-local-ip');

const API_PORT = process.env.API_PORT || 4242;
const ROOT_DIR = path.join(__dirname, '..');
const MOBILE_DIR = path.join(ROOT_DIR, 'mobile');

function createEnvFile(apiUrl) {
  const envLocalPath = path.join(MOBILE_DIR, '.env.development.local');
  const envContent = `# Auto-generated by dev-start.js - DO NOT COMMIT
# Generated at: ${new Date().toISOString()}
# This file is gitignored and will be regenerated on each dev start

EXPO_PUBLIC_API_URL=${apiUrl}
EXPO_PUBLIC_SOCKET_URL=${apiUrl}
`;

  fs.writeFileSync(envLocalPath, envContent);
  return envLocalPath;
}

async function start() {
  console.log('\n🚀 Starting Hantibink Development Environment\n');

  // Detect local IP
  const localIP = getLocalIP();
  const apiUrl = `http://${localIP}:${API_PORT}`;

  console.log(`📍 Local IP detected: ${localIP}`);
  console.log(`🔗 API URL: ${apiUrl}\n`);

  // Create .env.development.local
  const envPath = createEnvFile(apiUrl);
  console.log(`✅ Created ${path.relative(ROOT_DIR, envPath)}\n`);

  const metroPort = 8082;
  const metroUrl = `exp://${localIP}:${metroPort}`;

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📱 Open "Hantibink (Dev)" on your phone and scan:');
  console.log('');
  qrcode.generate(metroUrl, { small: true });
  console.log(`   Or enter manually: ${metroUrl}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  console.log('Starting servers... (logs will appear below)\n');

  // Start API and Expo concurrently
  const concurrently = spawn(
    'npx',
    [
      'concurrently',
      '--names',
      'API,EXPO',
      '--prefix-colors',
      'blue,magenta',
      '--kill-others-on-fail',
      '"npm run api"',
      '"cd mobile && npx expo start --dev-client --port 8082"',
    ],
    {
      stdio: 'inherit',
      shell: true,
      cwd: ROOT_DIR,
    }
  );

  concurrently.on('error', (err) => {
    console.error('❌ Failed to start:', err.message);
    process.exit(1);
  });

  concurrently.on('close', (code) => {
    if (code !== 0) {
      console.log(`\n⚠️  Process exited with code ${code}`);
    }
    process.exit(code);
  });

  // Handle Ctrl+C gracefully
  process.on('SIGINT', () => {
    console.log('\n\n👋 Shutting down...');
    concurrently.kill('SIGINT');
  });
}

start().catch((err) => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
