version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    container_name: hantibink-test-db
    environment:
      POSTGRES_DB: hantibink_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d hantibink_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data: