name: Migrate Database

on:
  push:
    branches:
      - main
    paths:
      - 'api/prisma/schema.prisma'
      - 'api/migrations/*.sql'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      
      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_POOLER_URL }}
        run: |
          # Run any SQL files in api/migrations folder
          for file in api/migrations/*.sql; do
            if [ -f "$file" ]; then
              echo "Running migration: $file"
              psql "$DATABASE_URL" < "$file"
            fi
          done