name: Mobile App Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'all'
        type: choice
        options:
          - android
          - ios
          - all
      profile:
        description: 'Build profile'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    name: Build Mobile App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json

      - name: Install dependencies
        working-directory: ./mobile
        run: npm ci

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        working-directory: ./mobile
        run: |
          PLATFORM="${{ github.event.inputs.platform || 'all' }}"
          PROFILE="${{ github.event.inputs.profile || 'production' }}"
          
          if [ "$PLATFORM" = "all" ]; then
            npx eas build --platform all --profile $PROFILE --non-interactive
          else
            npx eas build --platform $PLATFORM --profile $PROFILE --non-interactive
          fi

      - name: Get build URLs
        working-directory: ./mobile
        run: |
          echo "Build submitted to EAS!"
          echo "Check build status at: https://expo.dev/accounts/antoafarian/projects/hantibink/builds"