name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  migration-reminder:
    name: Migration Reminder
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for migration files
        uses: actions/github-script@v6
        with:
          script: |
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const hasSchemaChanges = files.data.some(f => 
              f.filename.includes('schema.prisma')
            );
            
            const hasPrismaMigration = files.data.some(f => 
              f.filename.includes('prisma/migrations/') && 
              f.filename.endsWith('.sql')
            );
            
            if (hasSchemaChanges && !hasPrismaMigration) {
              // Schema changed but no migration
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## ⚠️ Schema Change Detected
                
                This PR modifies \`schema.prisma\` but doesn't include a Prisma migration.
                
                **Required Actions:**
                1. Run \`npx prisma migrate dev --name your_migration_name\` to create a migration
                2. Test the migration locally
                3. Commit the generated migration files in \`prisma/migrations/\`
                
                **Production Deployment:**
                After merging, the migration will be automatically applied via \`npx prisma migrate deploy\`.`
              });
              
              core.setFailed('Schema changed without Prisma migration');
            } else if (hasSchemaChanges && hasPrismaMigration) {
              // Both present - good!
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## ✅ Migration Included
                
                This PR includes both schema changes and Prisma migration files.
                
                **After merging:** Migration will be automatically deployed to production.`
              });
            }